apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: shop
  namespace: openshift-gitops
spec:
  destination:
    name: ''
    namespace: gitops
    server: 'https://kubernetes.default.svc'
  source:
    path: helm/quarkus-helm-umbrella/chart
    repoURL:  https://github.com/shirodkar/cloud-native-deployment-strategies.git
    targetRevision: rollouts-blue-green
    helm:
      parameters:
      - name: "global.namespace"
        value: gitops
      valueFiles:
        - values/values-rollouts-blue-green.yaml
  project: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
